spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/curriculum'
    username: kukuking
    password: 112210ly
  sql:
    init:
      mode: always
server:
  port: 8080
logging:
  level:
    sql: debug
    com:
      example: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'


